import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopMenu from '@/components/TopMenu'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import ReduxProvider from '@/redux/features/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className="bg-transparent">
        <ReduxProvider>
        <NextAuthProvider session={session}>
          <TopMenu/>
          {children}
          <div className="fixed w-full h-full bg-white opacity-100 z-0"></div>
        </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
